"""implemented on delete cascade

Revision ID: 366d2e1fc18a
Revises: e3f63b274ce3
Create Date: 2025-12-22 16:15:19.488230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '366d2e1fc18a'
down_revision: Union[str, Sequence[str], None] = 'e3f63b274ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('allowed_voters_user_id_fkey'), 'allowed_voters', type_='foreignkey')
    op.drop_constraint(op.f('allowed_voters_election_id_fkey'), 'allowed_voters', type_='foreignkey')
    op.create_foreign_key(None, 'allowed_voters', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'allowed_voters', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('candidates_position_id_fkey'), 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('elections_creator_id_fkey'), 'elections', type_='foreignkey')
    op.create_foreign_key(None, 'elections', 'users', ['creator_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('positions_election_id_fkey'), 'positions', type_='foreignkey')
    op.create_foreign_key(None, 'positions', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('votes_position_id_fkey'), 'votes', type_='foreignkey')
    op.drop_constraint(op.f('votes_candidate_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_candidate_id_fkey'), 'votes', 'candidates', ['candidate_id'], ['id'])
    op.create_foreign_key(op.f('votes_position_id_fkey'), 'votes', 'positions', ['position_id'], ['id'])
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.create_foreign_key(op.f('positions_election_id_fkey'), 'positions', 'elections', ['election_id'], ['id'])
    op.drop_constraint(None, 'elections', type_='foreignkey')
    op.create_foreign_key(op.f('elections_creator_id_fkey'), 'elections', 'users', ['creator_id'], ['user_id'])
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key(op.f('candidates_position_id_fkey'), 'candidates', 'positions', ['position_id'], ['id'])
    op.drop_constraint(None, 'allowed_voters', type_='foreignkey')
    op.drop_constraint(None, 'allowed_voters', type_='foreignkey')
    op.create_foreign_key(op.f('allowed_voters_election_id_fkey'), 'allowed_voters', 'elections', ['election_id'], ['id'])
    op.create_foreign_key(op.f('allowed_voters_user_id_fkey'), 'allowed_voters', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
