"""Fixed db conflict in user model- delete orphan

Revision ID: 413a90202c03
Revises: 9ed7d16c9892
Create Date: 2025-12-24 19:37:08.731393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '413a90202c03'
down_revision: Union[str, Sequence[str], None] = '9ed7d16c9892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
