"""added proper type to the attempts and max attempts field

Revision ID: 5bc291158531
Revises: fd9482f3d5e0
Create Date: 2026-01-22 22:57:11.402266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5bc291158531'
down_revision: Union[str, Sequence[str], None] = 'fd9482f3d5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'forgotPasswordOtp', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'signupOtp', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signupOtp', type_='foreignkey')
    op.drop_constraint(None, 'forgotPasswordOtp', type_='foreignkey')
    # ### end Alembic commands ###
