"""modfied fullname field and added candidate_picture_id field in candidate model

Revision ID: 69b7222de067
Revises: 6f2b3be45040
Create Date: 2026-01-06 22:58:43.283657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69b7222de067'
down_revision: Union[str, Sequence[str], None] = '6f2b3be45040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('fullName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('candidates', sa.Column('candidate_picture_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('candidates', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('candidates', 'candidate_picture_id')
    op.drop_column('candidates', 'fullName')
    # ### end Alembic commands ###
