"""added constarint to vote model

Revision ID: 9ed7d16c9892
Revises: 366d2e1fc18a
Create Date: 2025-12-23 19:38:41.893084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ed7d16c9892'
down_revision: Union[str, Sequence[str], None] = '366d2e1fc18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('duplicate_vote', 'votes', ['user_id', 'position_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('duplicate_vote', 'votes', type_='unique')
    # ### end Alembic commands ###
