"""added election name field to election

Revision ID: c5ceed11b881
Revises: cc18333b4f79
Create Date: 2025-12-21 15:22:12.329163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5ceed11b881'
down_revision: Union[str, Sequence[str], None] = 'cc18333b4f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('election_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elections', 'election_name')
    # ### end Alembic commands ###
