"""added constraints to models

Revision ID: dabc54d70910
Revises: c5ceed11b881
Create Date: 2025-12-21 19:45:11.113094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dabc54d70910'
down_revision: Union[str, Sequence[str], None] = 'c5ceed11b881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_candidate_per_position', 'candidates', ['user_id', 'position_id'])
    op.create_unique_constraint('unique_Creator_election_name', 'elections', ['creator_id', 'election_name'])
    op.create_unique_constraint('unique_election_postion_name', 'positions', ['election_id', 'position_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_election_postion_name', 'positions', type_='unique')
    op.drop_constraint('unique_Creator_election_name', 'elections', type_='unique')
    op.drop_constraint('unique_candidate_per_position', 'candidates', type_='unique')
    # ### end Alembic commands ###
