"""removed constraints from candidate model

Revision ID: e3f63b274ce3
Revises: dabc54d70910
Create Date: 2025-12-22 07:47:25.337652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3f63b274ce3'
down_revision: Union[str, Sequence[str], None] = 'dabc54d70910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_candidate_per_position'), 'candidates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_candidate_per_position'), 'candidates', ['user_id', 'position_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
