"""added max attempts to otps

Revision ID: fd9482f3d5e0
Revises: b7c08d9bc906
Create Date: 2026-01-22 22:44:39.753170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd9482f3d5e0'
down_revision: Union[str, Sequence[str], None] = 'b7c08d9bc906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forgotPasswordOtp', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('forgotPasswordOtp', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('signupOtp', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('signupOtp', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signupOtp', 'attempts')
    op.drop_column('signupOtp', 'max_attempts')
    op.drop_column('forgotPasswordOtp', 'attempts')
    op.drop_column('forgotPasswordOtp', 'max_attempts')
    # ### end Alembic commands ###
